### ISSUE TITLE
What about using custom encoder?

### ISSUE THREAD

**Issue by 2hiTee** [aim-uofa/GenPercept#14]
Thanks for your excellent! I noticed in your paper that you utilized customized VAE decoder in your monocular depth estimation, which is part of DPT module. And you said all the prior knowledge of diffusion models is encapsulated within the U-Net. And you have demonstrated that changing of VAE decoder is acceptable. Currently, I am fitunting SD under the same architecture with yours and perhaps i need to change the VAE encoder. Have you ever tried with customized VAE encoder?  
Thanks for your help!

**Comment by guangkaixu** [comment]
Hi, thanks for your interest in our paper. In Table 9 of our earlier version (https://arxiv.org/pdf/2403.06090v2), we replace the VAE encoder with a customized one. The performance is less accurate, but we are not sure whether this is due to the wrong training paradigm of the VAE AutoEncoder. We only train it on Hypersim and supervise it with MSE loss. Hope this experiment can help you.

**Comment by 2hiTee** [comment]
> Hi, thanks for your interest in our paper. In Table 9 of our earlier version (https://arxiv.org/pdf/2403.06090v2), we replace the VAE encoder with a customized one. The performance is less accurate, but we are not sure whether this is due to the wrong training paradigm of the VAE AutoEncoder. We only train it on Hypersim and supervise it with MSE loss. Hope this experiment can help you.

Thanks for your reply and thanks for your great and massive experiements!
