### ISSUE TITLE
Quantitative result mismatch

### ISSUE THREAD

**Issue by jk4011** [aim-uofa/GenPercept#4]
Hello, and thank you for your excellent work. 
I noticed that the quantitative results from tables 1, 9, 10, and 12 differ. 
For example, the KITTI-AbsRel scores for GenPercept (or Baseline) are 0.099, 0.140, 0.145, and 0.140, respectively. 
Could you help me understand what I might be missing?

**Comment by guangkaixu** [comment]
For table 1, the model is trained on Hypersim + Virtual KITTI. For tables 9, 10, and 12, these models are trained on Hypersim only. 

For tables 9 and 12, they are trained with a batchsize of 16, but it changed to 8 for tale 10. It seems that we forgot to mention it in our paper, and we will update it in the future. 

The reason for changing the batchsize to 8 is that  GenPercent (PixArt-α) can not be trained for batchsize 16 because of "CUDA out of memory" on A800.
