### ISSUE TITLE
Question about GenPercept performance

### ISSUE THREAD

**Issue by gwang-kim** [aim-uofa/GenPercept#5]
Hi there,

Thank you for your great work on GenPercept!  The idea of one-step estimation is very promising.

I noticed that the performance of GenPercept seems to be lower than Marigold and GeoWizard. I'm wondering if this difference is due to:
- The number of estimation steps (multi-step vs. one-step)?
- The amount of training data used?
- A combination of both factors?

Any insights you could provide would be greatly appreciated!

**Comment by guangkaixu** [comment]
Hi, sorry for the late response. It seems that my e-mail didn't notice me this issue in GitHub. 

Although we tried to reproduce Marigold by ourselves (the training code of Marigold was not released) , we can hardly reach the performance in their paper. In order to compare fairly, we compare Marigold and GenPercept under the same training setting, and  the results can be seen in Table 7 of the main paper.
![image](https://github.com/aim-uofa/GenPercept/assets/46716149/aa533631-f475-4df2-b221-0a6b3edabae2)

"Stochastic MS Gen." here actually means Marigold trained by ourselves, and the performance is slightly worse than the training paradigm GenPercept in the depth estimation task.
